# Generated by Django 6.0.7 on 2026-08-09 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_remove_supplier_name_supplier_contact_person_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('VIEWER', 'Viewer (Check Stock Only)'), ('EMPLOYEE', 'Employee (Stock & Orders)'), ('MANAGER', 'Manager (Full Access)')], default='VIEWER', max_length=20)),
                ('requested_role', models.CharField(choices=[('VIEWER', 'Viewer (Check Stock Only)'), ('EMPLOYEE', 'Employee (Stock & Orders)'), ('MANAGER', 'Manager (Full Access)')], default='EMPLOYEE', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('can_add_product', models.BooleanField(default=False)),
                ('can_create_bill', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
