# Generated by Django 6.0.7 on 2026-08-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='can_view_reports',
        ),
        migrations.AddField(
            model_name='profile',
            name='can_export_reports',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_manage_suppliers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_view_financials',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='requested_role',
            field=models.CharField(choices=[('VIEWER', 'Viewer (Check Stock Only)'), ('SALES', 'Sales Agent (Invoicing & Customer Orders)'), ('CLERK', 'Stock Clerk (Inventory & Quantities)'), ('PURCHASER', 'Procurement (Suppliers & Reordering)'), ('ACCOUNTANT', 'Accountant (Financials & Reports)'), ('MANAGER', 'Store Manager (Full Operational Access)'), ('ADMIN', 'System Admin (User Approvals & Settings)')], default='CLERK', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('VIEWER', 'Viewer (Check Stock Only)'), ('SALES', 'Sales Agent (Invoicing & Customer Orders)'), ('CLERK', 'Stock Clerk (Inventory & Quantities)'), ('PURCHASER', 'Procurement (Suppliers & Reordering)'), ('ACCOUNTANT', 'Accountant (Financials & Reports)'), ('MANAGER', 'Store Manager (Full Operational Access)'), ('ADMIN', 'System Admin (User Approvals & Settings)')], default='VIEWER', max_length=20),
        ),
    ]
