# Generated by Django 6.0.7 on 2026-08-10 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_remove_profile_can_view_reports_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='created_at',
        ),
        migrations.AddField(
            model_name='customer',
            name='total_paid_by_customer',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_purchased_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='supplier',
            name='name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='total_paid_to_supplier',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='supplier',
            name='total_supplied_value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profile',
            name='requested_role',
            field=models.CharField(choices=[('VIEWER', 'Viewer (Check Stock Only)'), ('SALES', 'Sales Agent (Invoicing & Customer Orders)'), ('CLERK', 'Stock Clerk (Inventory & Quantities)'), ('PURCHASER', 'Procurement (Suppliers & Reordering)'), ('ACCOUNTANT', 'Accountant (Financials & Reports)'), ('MANAGER', 'Store Manager (Full Operational Access)'), ('ADMIN', 'System Admin (User Approvals & Settings)'), ('SUPPLIER', 'External Supplier Portal'), ('CUSTOMER', 'External Customer Portal')], default='CLERK', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('VIEWER', 'Viewer (Check Stock Only)'), ('SALES', 'Sales Agent (Invoicing & Customer Orders)'), ('CLERK', 'Stock Clerk (Inventory & Quantities)'), ('PURCHASER', 'Procurement (Suppliers & Reordering)'), ('ACCOUNTANT', 'Accountant (Financials & Reports)'), ('MANAGER', 'Store Manager (Full Operational Access)'), ('ADMIN', 'System Admin (User Approvals & Settings)'), ('SUPPLIER', 'External Supplier Portal'), ('CUSTOMER', 'External Customer Portal')], default='VIEWER', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
