# Generated by Django 6.0.7 on 2026-08-10 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0013_remove_customer_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='invoice_number',
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tracker.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='quantity',
            field=models.PositiveIntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invoice',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='party_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='transaction_type',
            field=models.CharField(choices=[('IN', 'Inward (Purchase)'), ('OUT', 'Outward (Sale)')], default='OUT', max_length=3),
        ),
    ]
